version: '3'
services:
  pingpong_agent:
    image: tabletennis_agent_random
    hostname: agent
    env_file:
      - docker/agent/docker.env
    build:
      context: ./
      dockerfile: docker/agent/Dockerfile_AgentTabletennis_random
